config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-carmine-hummingbird.sh
        container: qc.acc_hasty-corn-hippopotamus
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-platinum-sponge.sh
        container: qc.doc_sunny-sepia-tzu
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-persimmon-dolphin.sh
        container: qc.doc_shabby-wheat-spitz
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-harlequin-walrus.sh
        container: qc.lic_blurry-yellow-duck
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-sepia-badger.sh
        container: qc.ver_pretty-khaki-chicken
timeout: 5400
